# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
  pull_request:
  schedule:
    - cron: '1 * * * *'
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - uses: bahmutov/npm-install@v1.6.0
      - name: Run scraper
        run: node ./packages/coinmarket-cap-scraper/src/puppeteer/puppeteerFactory.js

